export const experience = [
  {
    company: "Busify",
    title: "Full Stack Web Developer",
    date: "Present",
    data: [
      {
        title: "AWS Certified",
        subTitle: "AWS Certified Cloud Practitioner - Associate",
      },
      { subTitle: "Promoted Nov 2022" },
    ],
    details: "I currently hold a leading role here with responsibility working on frontend, backend, infrastructure, task management, contributing to designs, managing other developers, and resolving customer feedback.",
  },
  {
    company: "TATA Consultancy Services",
    title: "Junior Software Engineer",
    date: "Feb 2022",
    details: "Allocated to Boeing to monitor and support an internal Java application.",
  },
  {
    company: "University of Illinois Urbana-Champaign",
    title: "B.S. Computer Engineering",
    date: "May 2021",
    data: [
      { title: "Software Engineer", subTitle: "Oculo.AI", details: "Built an internal Python tool to accelerate the product's pipeline and improve ease of use." },
      { title: "Frontend Developer", subTitle: "All-Time Yachting", details: "Took on various tasks as a frontend developer to help the team." },
      { title: "Frontend Developer", subTitle: "MUS-ROVER", details: "Contributed to a machine learning research project." },
      { title: "IT Intern", subTitle: "John Deere", details: "Handled DevOps requests for all repositories and assisted in developing tests." },
    ],
  },
];

export const projects = [
  {
    title: ["Legacy"],
    colors: ["#72EFF1", "#25E0CD", "#EC52CA", "#FF3D60", "#7416EC"],
    desc: "A desktop / mobile app combo for task management, reminders, and habit building. It uses the latest productivity and health research to increase a user's potential while supporting healthy life choices.",
    type: "Apps",
    status: "In development",
    dates: "JAN 2024 - PRESENT",
    tech: [
      "Electron",
      "TypeScript",
      "React",
      "Tailwind",
      "Sass",
      "Node.js",
      "MySQL",
      "Jest",
    ],
    images: [
      "/Todo.png",
      "/legacy-2.png",
      "/legacy1.png",
      "/legacy2.png",
      "/legacy3.png",
      "/legacy4.png",
    ],
  },
  {
    title: ["Wordle", "FR"],
    colors: ["#629F5B", "#C2AA52", "#FFFFFF", "#000000"],
    desc: "A Wordle clone for the French side of the family, it features a list of 365 french words and full Wordle functionality. Last I heard they have a whole WhatsApp chat for discussing the word of the day and sharing how many tries it took them to guess it!",
    type: "Website",
    status: "Completed",
    dates: "JAN 2022",
    tech: ["Next.js", "JavaScript", "CSS"],
    images: [
      "/wordlefr-1.png",
      "/wordlefr-2.png",
      "/wordlefr1.png",
      "/wordlefr2.png",
      "/wordlefr3.png",
      "/wordlefr4.png",
    ],
  },
  {
    title: ["TENEEZ"],
    colors: ["#F2B822", "#FFFFFF", "#000000"],
    desc: "A startup that gives users a place to rent the coolest and most exclusive sneakers. Cofounded by myself and a friend in my junior year of college, I was CTO and sole designer / frontend developer. We ran for over a year before closing.",
    type: "Startup",
    status: "Closed",
    dates: "NOV 2019 - JUN 2021",
    tech: [
      "React",
      "Next.js",
      "React Native",
      "JavaScript",
      "MySQL",
      "Node.js",
      "AWS",
      "Stripe",
    ],
    images: [
      "/teneez-1.png",
      "/teneez-2.png",
      "/teneez1.png",
      "/teneez2.png",
      "/teneez3.png",
      "/teneez4.png",
    ],
  },
  {
    title: ["CV Site", "v1"],
    colors: ["#26D8D6", "#3591DC", "#5D65B4", "#D52828", "#000000"],
    desc: "The last version of this website! Built over winter break in 2021 in hopes of landing a job at a startup, there were some cool pieces in there. I just think it's fun to look back and see how far I've come.",
    type: "Website",
    status: "Deprecated",
    dates: "JAN 2021",
    tech: ["Next.js", "React", "Smooth Scroll", "CSS"],
    images: [
      "/personal-1.png",
      "/personal-2.png",
      "/personal1.png",
      "/personal2.png",
      "/personal3.png",
      "/personal4.png",
    ],
  },
];

export const config = {
  SIM_RESOLUTION: 128,
  DYE_RESOLUTION: 1024,
  CAPTURE_RESOLUTION: 512,
  DENSITY_DISSIPATION: 6,
  VELOCITY_DISSIPATION: 0.6,
  PRESSURE: 0.8,
  PRESSURE_ITERATIONS: 20,
  CURL: 0,
  SPLAT_RADIUS: 0.004,
  SPLAT_FORCE: 20000,
  SHADING: true,
  COLORFUL: false,
  COLOR_UPDATE_SPEED: 10,
  PAUSED: false,
  BACK_COLOR: { r: 255, g: 255, b: 255 },
  TRANSPARENT: true,
  BLOOM: false,
  BLOOM_ITERATIONS: 6,
  BLOOM_RESOLUTION: 256,
  BLOOM_INTENSITY: 0.05,
  BLOOM_THRESHOLD: 0.8,
  BLOOM_SOFT_KNEE: 0.7,
  SUNRAYS: true,
  SUNRAYS_RESOLUTION: 196,
  SUNRAYS_WEIGHT: 1.0,
};

export const aboutMe = [
  "I pride myself in hard work, a constant desire to learn, and a broad skill set. I have experience working across the entire pipeline, from idea to release, with projects to back it up. Lately, my choice of stack is Next.js with Tailwind, a Node.js backend, and MySQL. I'm also trying to get back into mobile app development with React Native.",
  "Don't worry, I'm not all work. I love throwing myself into new hobbies and expanding on old ones. Some longer lasting interests include photography, fitness, and traveling. More recently, you might find me running, listening to an audiobook, or perfecting my homemade kombucha. A couple of my new year's resolutions are to run a marathon and read 50 books!",
  "Hope you like my website :)",
];
